# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/xivo-agid/conf.d/

# Owned of the process
user: xivo-agid

# Change the log level to debug level.
debug: false

# Log file.
logfile: /var/log/xivo-agid.log

# PID file.
pidfile: /var/run/xivo-agid/xivo-agid.pid

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@localhost/asterisk

# AGI server listening informations.
listen_address: 127.0.0.1
listen_port: 4573

# xivo-agentd connection informations.
agentd:
  host: localhost
  verify_certificate: /usr/share/xivo-certs/server.crt

# xivo-dird connection informations.
dird:
  host: localhost
  port: 9489
  timeout: 1
  verify_certificate: /usr/share/xivo-certs/server.crt

# xivo-auth connection informations.
auth:
  host: localhost
  port: 9497
  key_file: /var/lib/xivo-auth-keys/xivo-agid-key.yml
  verify_certificate: /usr/share/xivo-certs/server.crt

# xivo-confd connection information
confd:
  host: localhost
  port: 9486
  https: True
  verify_certificate: /usr/share/xivo-certs/server.crt

# Event bus (AMQP) connection informations
bus:
  username: guest
  password: guest
  host: localhost
  port: 5672
  exchange_name: xivo
  exchange_type: topic
  exchange_durable: True

call_recording:
  filename_template: "user-{{ srcnum }}-{{ dstnum }}-{{ timestamp }}"
  filename_extension: wav
