# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files to the extra_config_files directory to override
# the settings in this file

# Directory in which to place config overrides
extra_config_files: /etc/wazo-agid/conf.d/

# Owner of the process
user: wazo-agid

# Change the log level to debug.
debug: false

# Log file.
logfile: /var/log/wazo-agid.log

# Database connection settings
db_uri: postgresql://asterisk:proformatique@localhost/asterisk?application_name=wazo-agid

# AGI server settings
listen_address: 127.0.0.1
listen_port: 4573

# wazo-agentd connection settings
agentd:
  host: localhost
  port: 9493
  prefix: null
  https: false

# wazo-dird connection settings
dird:
  host: localhost
  port: 9489
  prefix: null
  https: false
  timeout: 1

# wazo-auth connection settings
auth:
  host: localhost
  port: 9497
  prefix: null
  https: false
  key_file: /var/lib/wazo-auth-keys/wazo-agid-key.yml

# wazo-confd connection settings
confd:
  host: localhost
  port: 9486
  prefix: null
  https: false
