# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/wazo-agid/conf.d/

# Owned of the process
user: wazo-agid

# Change the log level to debug level.
debug: false

# Log file.
logfile: /var/log/wazo-agid.log

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@localhost/asterisk

# AGI server listening informations.
listen_address: 127.0.0.1
listen_port: 4573

# wazo-agentd connection informations.
agentd:
  host: localhost
  port: 9493
  prefix: null
  https: false

# wazo-dird connection informations.
dird:
  host: localhost
  port: 9489
  prefix: null
  https: false
  timeout: 1

# wazo-auth connection informations.
auth:
  host: localhost
  port: 9497
  prefix: null
  https: false
  key_file: /var/lib/wazo-auth-keys/wazo-agid-key.yml

# wazo-confd connection information
confd:
  host: localhost
  port: 9486
  prefix: null
  https: false

# Event bus (AMQP) connection informations
bus:
  username: guest
  password: guest
  host: localhost
  port: 5672
  exchange_name: xivo
  exchange_type: topic
  exchange_durable: True

call_recording:
  filename_template: "/var/lib/wazo/sounds/tenants/{{ tenant_uuid }}/monitor/{{ dest_type }}-{{ srcnum }}-{{ dstnum }}-{{ timestamp }}"
  filename_extension: wav
